import {combineReducers} from 'redux';

import pivotTableReducer from './PivotTableReducer'

import {loginReducer, loginFormReducer, registerFormReducer} from './UserAuthenticationReducers'

import homeScreenReducer from './HomeScreenReducer'

// action types
const C = {
  FETCH_TABLE_LIST: 'FETCH_TABLE_LIST',
  FETCH_TABLE_LIST_SUCCESS: 'FETCH_TABLE_LIST_SUCCESS',
  FETCH_TABLE_LIST_ERROR: 'FETCH_TABLE_LIST_ERROR',
  TABLE_SELECTED: 'TABLE_SELECTED',
  CONNECT_DATA_SOURCE: 'CONNECT_DATA_SOURCE',
  CONNECT_DATA_SOURCE_SUCCESS: 'CONNECT_DATA_SOURCE_SUCCESS',
  CONNECT_DATA_SOURCE_ERROR: 'CONNECT_DATA_SOURCE_ERROR',
  USERNAME_CHANGED: 'USERNAME_CHANGED',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  DATASOURCE_CHANGED: 'DATASOURCE_CHANGED',
  DISCONNECT: 'DISCONNECT',
  FETCH_RAW_REPORT: 'FETCH_RAW_REPORT',
  FETCH_RAW_REPORT_SUCCESS: 'FETCH_RAW_REPORT_SUCCESS',
  FETCH_RAW_REPORT_ERROR: 'FETCH_RAW_REPORT_ERROR',
  SCHEMA_ROW_LABELS_SELECTED: 'SCHEMA_ROW_LABELS_SELECTED',
  SCHEMA_COLUMN_LABELS_SELECTED: 'SCHEMA_COLUMN_LABELS_SELECTED',
  SCHEMA_PAGE_LABEL_SELECTED: 'SCHEMA_PAGE_LABEL_SELECTED',
  SCHEMA_FUNCTION_SELECTED: 'SCHEMA_FUNCTION_SELECTED',
  SCHEMA_VALUE_SELECTED: 'SCHEMA_VALUE_SELECTED',
  SCHEMA_RESET: 'SCHEMA_RESET',
  GENERATE_PIVOT_TABLE: 'GENERATE_PIVOT_TABLE',
  GENERATE_PIVOT_TABLE_SUCCESS: 'GENERATE_PIVOT_TABLE_SUCCESS',
  GENERATE_PIVOT_TABLE_ERROR: 'GENERATE_PIVOT_TABLE_ERROR',
  PIVOT_TABLE_PAGE_CHANGED: 'PIVOT_TABLE_PAGE_CHANGED',
  FETCH_FILTER_FIELDS: 'FETCH_FILTER_FIELDS',
  FETCH_FILTER_FIELDS_SUCCESS: 'FETCH_FILTER_FIELDS_SUCCESS',
  FETCH_FILTER_FIELDS_FAILURE: 'FETCH_FILTER_FIELDS_FAILURE',
  SORT_FIELD_SELECTED: 'SORT_FIELD_SELECTED',
  SORT_ORDER_SELECTED: 'SORT_ORDER_SELECTED',
  FILTER_FIELD_SELECTED: 'FILTER_FIELD_SELECTED',
  FILTER_VALUE_SELECTED: 'FILTER_VALUE_SELECTED',
  TOGGLE_PRINTABLE_VIEW: 'TOGGLE_PRINTABLE_VIEW',
  SCHEMA_LABEL_ALIAS_CHANGED: 'SCHEMA_LABEL_ALIAS_CHANGED',
  SCHEMA_SUMMARY_FUNCTION_SELECTED: 'SCHEMA_SUMMARY_FUNCTION_SELECTED',
  LOGIN_USERNAME_CHANGED: 'LOGIN_USERNAME_CHANGED',
  LOGIN_PASSWORD_CHANGED: 'LOGIN_PASSWORD_CHANGED',
  REGISTER_USERNAME_CHANGED: 'REGISTER_USERNAME_CHANGED',
  REGISTER_PASSWORD1_CHANGED: 'REGISTER_PASSWORD1_CHANGED',
  REGISTER_PASSWORD2_CHANGED: 'REGISTER_PASSWORD2_CHANGED',
  LOGIN_SUBMIT: 'LOGIN_SUBMIT',
  LOGIN_SUBMIT_SUCCESS: 'LOGIN_SUBMIT_SUCCESS',
  LOGIN_SUBMIT_FAILURE: 'LOGIN_SUBMIT_FAILURE',
  REGISTER_SUBMIT: 'REGISTER_SUBMIT',
  REGISTER_SUBMIT_SUCCESS: 'REGISTER_SUBMIT_SUCCESS',
  REGISTER_SUBMIT_FAILURE: 'REGISTER_SUBMIT_FAILURE',
  FETCH_USER_INFO: 'FETCH_USER_INFO',
  FETCH_USER_INFO_SUCCESS: 'FETCH_USER_INFO_SUCCESS',
  FETCH_USER_INFO_FAILURE: 'FETCH_USER_INFO_FAILURE',
  LOGOUT: 'LOGOUT',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAILURE: 'LOGOUT_FAILURE',
  PIVOT_TABLE_CLEAR: 'PIVOT_TABLE_CLEAR', // clears the store
  FETCH_SHAREABLE_SCHEMA: 'FETCH_SHAREABLE_SCHEMA',
  FETCH_SHAREABLE_SCHEMA_SUCCESS: 'FETCH_SHAREABLE_SCHEMA_SUCCESS',
  FETCH_SHAREABLE_SCHEMA_SET_ALIAS: 'FETCH_SHAREABLE_SCHEMA_SET_ALIAS',
  FETCH_SHAREABLE_SCHEMA_FAILURE: 'FETCH_SHAREABLE_SCHEMA_FAILURE',
  SAVE_SHAREABLE_SCHEMA: 'SAVE_SHAREABLE_SCHEMA',
  SAVE_SHAREABLE_SCHEMA_SUCCESS: 'SAVE_SHAREABLE_SCHEMA_SUCCESS',
  SAVE_SHAREABLE_SCHEMA_FAILURE: 'SAVE_SHAREABLE_SCHEMA_FAILURE',
  SCHEMA_NAME_CHANGED: 'SCHEMA_NAME_CHANGED',
  FETCH_ALL_USER_SCHEMAS: 'FETCH_ALL_USER_SCHEMAS',
  FETCH_ALL_USER_SCHEMAS_SUCCESS: 'FETCH_ALL_USER_SCHEMAS_SUCCESS',
  FETCH_ALL_USER_SCHEMAS_FAILURE: 'FETCH_ALL_USER_SCHEMAS_FAILURE',
  REMOVE_SHARED_SCHEMA: 'REMOVE_SHARED_SCHEMA',
  REMOVE_SHARED_SCHEMA_SUCCESS: 'REMOVE_SHARED_SCHEMA_SUCCESS',
  REMOVE_SHARED_SCHEMA_FAILURE: 'REMOVE_SHARED_SCHEMA_FAILURE',
  DELETE_MY_SCHEMA: 'DELETE_MY_SCHEMA',
  DELETE_MY_SCHEMA_SUCCESS: 'DELETE_MY_SCHEMA_SUCCESS',
  DELETE_MY_SCHEMA_FAILURE: 'DELETE_MY_SCHEMA_FAILURE',
  STOP_SHARING_SCHEMA: 'STOP_SHARING_SCHEMA',
  STOP_SHARING_SCHEMA_SUCCESS: 'STOP_SHARING_SCHEMA_SUCCESS',
  STOP_SHARING_SCHEMA_FAILURE: 'STOP_SHARING_SCHEMA_FAILURE',
  ADD_USER_TO_SHARED_SCHEMA: 'ADD_USER_TO_SHARED_SCHEMA',
  ADD_USER_TO_SHARED_SCHEMA_SUCCESS: 'ADD_USER_TO_SHARED_SCHEMA_SUCCESS',
  ADD_USER_TO_SHARED_SCHEMA_FAILURE: 'ADD_USER_TO_SHARED_SCHEMA_FAILURE',
  LOAD_SHARED_USERS: 'LOAD_SHARED_USERS',
  LOAD_SHARED_USERS_SUCCESS: 'LOAD_SHARED_USERS_SUCCESS',
  LOAD_SHARED_USERS_FAILURE: 'LOAD_SHARED_USERS_FAILURE',
  NEW_USER_TO_SHARE_VALUE_CHANGED: 'NEW_USER_TO_SHARE_VALUE_CHANGED',
  CLOSE_SHARED_USERS_MODAL: 'CLOSE_SHARED_USERS_MODAL',
  IMPORT_SCHEMA_MODAL_OPEN: 'IMPORT_SCHEMA_MODAL_OPEN',
  IMPORT_SCHEMA_MODAL_CLOSE: 'IMPORT_SCHEMA_MODAL_CLOSE',
  IMPORT_SCHEMA: 'IMPORT_SCHEMA',
  IMPORT_SCHEMA_SUCCESS: 'IMPORT_SCHEMA_SUCCESS',
  IMPORT_SCHEMA_FAILURE: 'IMPORT_SCHEMA_FAILURE',
  HOME_DISMISS_INFO: 'HOME_DISMISS_INFO',
  IMPORT_SCHEMA_FILE_SELECTED: 'IMPORT_SCHEMA_FILE_SELECTED',
}


const getPivotTableState = (state) => (state.pivotTableReducer)
const getLoginFormState = (state) => (state.loginFormReducer)
const getAuthenticationState = (state) => (state.loginReducer)
const getRegisterFormState = (rootstate) => (rootstate.registerFormReducer)
const getHomeScreenState = (rootState) => (rootState.homeScreenReducer)

export {
  C,
  getPivotTableState,
  getLoginFormState,
  getAuthenticationState,
  getRegisterFormState,
  getHomeScreenState
}

export default combineReducers({
  pivotTableReducer,
  loginReducer,
  loginFormReducer,
  registerFormReducer,
  homeScreenReducer
})

